import { Product } from '@/types'

export const products: Product[] = [
  {
    id: '1',
    name: 'Fresh Full Cream Milk',
    description: 'Pure farm-fresh full cream milk collected daily. Rich in calcium and vitamins.',
    price: 180,
    unit: '1 Liter',
    category: 'fresh',
    emoji: '🥛',
    inStock: true,
    badge: 'bestseller',
    rating: 4.8,
    reviews: 234,
  },
  {
    id: '2',
    name: 'Organic Cow Milk',
    description: 'Certified organic milk from grass-fed cows. No hormones, no antibiotics.',
    price: 280,
    unit: '1 Liter',
    category: 'organic',
    emoji: '🐄',
    inStock: true,
    badge: 'organic',
    rating: 4.9,
    reviews: 156,
  },
  {
    id: '3',
    name: 'Chocolate Milk',
    description: 'Delicious chocolate-flavored milk. Kids love it! Made with real cocoa.',
    price: 220,
    unit: '500ml',
    category: 'flavored',
    emoji: '🍫',
    inStock: true,
    badge: 'new',
    rating: 4.7,
    reviews: 89,
  },
  {
    id: '4',
    name: 'Strawberry Milk',
    description: 'Sweet strawberry-flavored milk made with natural strawberry extract.',
    price: 220,
    unit: '500ml',
    category: 'flavored',
    emoji: '🍓',
    inStock: true,
    rating: 4.6,
    reviews: 67,
  },
  {
    id: '5',
    name: 'Fresh Cream',
    description: 'Rich, thick fresh cream perfect for cooking, baking, and desserts.',
    price: 350,
    unit: '500ml',
    category: 'cream',
    emoji: '🍦',
    inStock: true,
    rating: 4.8,
    reviews: 112,
  },
  {
    id: '6',
    name: 'Pure Butter',
    description: 'Churned from fresh cream. Rich golden butter for cooking and spreading.',
    price: 420,
    unit: '250g',
    category: 'butter',
    emoji: '🧈',
    inStock: true,
    badge: 'bestseller',
    rating: 4.9,
    reviews: 198,
  },
  {
    id: '7',
    name: 'Natural Yogurt',
    description: 'Thick, creamy yogurt made from fresh milk. Probiotic-rich and healthy.',
    price: 200,
    unit: '500g',
    category: 'yogurt',
    emoji: '🫙',
    inStock: true,
    rating: 4.7,
    reviews: 143,
  },
  {
    id: '8',
    name: 'Low Fat Milk',
    description: 'All the goodness of fresh milk with reduced fat. Perfect for a healthy diet.',
    price: 160,
    unit: '1 Liter',
    category: 'fresh',
    emoji: '💧',
    inStock: true,
    badge: 'sale',
    discount: 10,
    rating: 4.5,
    reviews: 78,
  },
  {
    id: '9',
    name: 'Buffalo Milk',
    description: 'Rich, creamy buffalo milk. Higher fat content, ideal for making sweets.',
    price: 200,
    unit: '1 Liter',
    category: 'fresh',
    emoji: '🐃',
    inStock: false,
    rating: 4.8,
    reviews: 321,
  },
  {
    id: '10',
    name: 'Mango Lassi Mix',
    description: 'Ready-to-blend mango lassi mix. Just add milk and blend!',
    price: 250,
    unit: '400g',
    category: 'flavored',
    emoji: '🥭',
    inStock: true,
    badge: 'new',
    rating: 4.6,
    reviews: 45,
  },
  {
    id: '11',
    name: 'Organic Yogurt',
    description: 'Certified organic yogurt made from organic milk. Smooth and tangy.',
    price: 320,
    unit: '500g',
    category: 'organic',
    emoji: '🌿',
    inStock: true,
    badge: 'organic',
    rating: 4.8,
    reviews: 92,
  },
  {
    id: '12',
    name: 'Whipped Cream',
    description: 'Light and fluffy whipped cream. Perfect for cakes and desserts.',
    price: 380,
    unit: '250ml',
    category: 'cream',
    emoji: '🎂',
    inStock: true,
    rating: 4.7,
    reviews: 67,
  },
]

export const categories = [
  { id: 'all',      label: 'All Products', emoji: '🛒' },
  { id: 'fresh',    label: 'Fresh Milk',   emoji: '🥛' },
  { id: 'organic',  label: 'Organic',      emoji: '🌿' },
  { id: 'flavored', label: 'Flavored',     emoji: '🍓' },
  { id: 'cream',    label: 'Cream',        emoji: '🍦' },
  { id: 'butter',   label: 'Butter',       emoji: '🧈' },
  { id: 'yogurt',   label: 'Yogurt',       emoji: '🫙' },
]

export const mockOrders = [
  {
    id: 'ORD-001',
    items: [{ product: products[0], quantity: 2 }, { product: products[5], quantity: 1 }],
    customer: { name: 'Ahmed Ali', email: 'ahmed@gmail.com', phone: '03001234567', address: 'House 12, Street 4', city: 'Lahore' },
    payment: { method: 'cash', status: 'paid' },
    status: 'delivered',
    total: 780,
    createdAt: '2026-05-20T10:30:00Z',
  },
  {
    id: 'ORD-002',
    items: [{ product: products[1], quantity: 3 }],
    customer: { name: 'Fatima Khan', email: 'fatima@gmail.com', phone: '03121234567', address: 'Flat 5, Block B', city: 'Karachi' },
    payment: { method: 'jazzcash', status: 'paid' },
    status: 'delivering',
    total: 840,
    createdAt: '2026-05-24T14:15:00Z',
  },
  {
    id: 'ORD-003',
    items: [{ product: products[2], quantity: 4 }, { product: products[6], quantity: 2 }],
    customer: { name: 'Usman Malik', email: 'usman@gmail.com', phone: '03331234567', address: 'Plot 8, Sector F', city: 'Islamabad' },
    payment: { method: 'card', status: 'pending' },
    status: 'pending',
    total: 1280,
    createdAt: '2026-05-25T09:00:00Z',
  },
]
